#include <stdio.h>
#include <stdlib.h>
int wickets, overs;
typedef struct player
{
    int playerno, ind_runs, ind_wickets;
    float average, economy, strike_rate;
    char player_type[7], player_name[25];
} player;
struct score
{
    int team_score;
    int total_overs;
    int total_wickets;
    player player;
};

int print_rules()
{
    int n;
    printf("\033[1;33m");
    printf("\n---------------------------------------------------------Welcome to Our Key-Cricket Game------------------------------------------------------------");
    printf("\n\nKey Cricket is a game designed by students of DIST students to help students overcome stress and have fun!");
    printf("\n\nThe name Key-Cricket is so because you will be playing using your computer/laptop keyboard vs our super intelligent computer!!");
    printf("\n\n\n");
    printf("Let's Jump on to the Rules of The game");
    printf("\033[1;32m");
    printf("\n\nRules of the Game:\n");
    printf("\033[1;31m");
    printf("\n\n1.The User has to spin a coin during the toss,based on the outcome of the toss, the user will bat or field first!");
    printf("\n\n3.The User can choose the total number of overs and wickets for the respective match after the toss.");
    printf("\n\n4.The User can enter scores only between 0 to 6.");
    printf("\n\n5.If the User and computer land up on the same number while batting, the batsman is declared out.");
    printf("\n\n6.The team is considered ALL OUT after losing all the wickets during batting.");
    printf("\n\n7.If the batsman inputs a 0 and the computer generates any number other than 0,those runs will be added to the batsman's score.");
    printf("\n\n8.In case of a 0 by both the batsman and the computer, then the batsman is declared out.");
    printf("\n\n9.A batsman is considered to be out when he inputs the same number as that of the number generated by the opponent.");
    printf("\033[1;35m");
    printf("\n\nARE YOU READY FOR THE GAME?If yes, Please enter 1.");
    printf("\033[0;m");
    printf("\n\n");
    printf("START THE GAME?PRESS 1\n");
    scanf("%d", &n);
    return n;
}
void start()
{
    printf("\nEnter the No of wickets(1-5):");
    scanf("%d", &wickets);
    while (wickets > 5)
    {
        printf("\nEnter the No of wickets in the given range : 1-5 :");
        scanf("%d", &wickets);
    }
    printf("Enter the No of Overs(1-6):");
    scanf("%d", &overs);
    while (overs > 6)
    {
        printf("\nEnter the No of overs in the given range : 1-6 :");
        scanf("%d", &overs);
    }
}
void toss()
{
    printf("\nTossss!!\n");
}
void main()
{
    int t = print_rules();
    if (t == 1)
        printf("\nStarting...\n");
    start();
    printf("\nNo of Wickets in this Match : %d", wickets);
    printf("\nNo of Overs in this Match : %d\n", overs);
    printf("\nIts Toss Times!!\n");
    toss();
}